class ProductoLocal {
  final String id;
  final String nombre;
  final String descripcion;
  final int precio;
  final String imagenUrl;
  final String categoriaId;
  final List<String> tallas;
  final int stock;

  ProductoLocal({
    required this.id,
    required this.nombre,
    required this.descripcion,
    required this.precio,
    required this.imagenUrl,
    required this.categoriaId,
    required this.tallas,
    required this.stock,
  });
}

// Datos fijos (solo con tallas)
final List<ProductoLocal> productosFijos = [
  // NIKE 1.1
  ProductoLocal(
    id: '1',
    nombre: 'T JAYS AZUL',
    descripcion: 'Gorra de los Toronto Jays 2 Tonos Azules Modelo 2025',
    precio: 59000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762950181/gorrastaysazulsocuro14_mt0k0o.jpg',
    categoriaId: '1',
    tallas: ['Ajustable'],
    stock: 10,
  ),
 ProductoLocal(
  id: '2',
  nombre: 'GORRA ROJA Y MORADA',
  descripcion: 'Gorra deportiva con diseño vibrante en rojo y morado, ideal para el estilo urbano.',
  precio: 89000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762950188/gorrarojaymorada9_sufoqt.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 12,
),
ProductoLocal(
  id: '3',
  nombre: 'GORRA AZUL DEL BULLDOG',
  descripcion: 'Diseño exclusivo con estampado de bulldog en tonos azules, perfecta para fans de lo urbano.',
  precio: 92000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762949687/gorrasazuldelbuldog_ebyrlc.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 8,
),
ProductoLocal(
  id: '4',
  nombre: 'GORRA GRIS DEL ELEFANTE',
  descripcion: 'Estilo premium con ilustración de elefante en gris sobrio, para un look elegante y diferente.',
  precio: 90000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762950188/gorrasgriselfante8_czzieu.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 10,
),
ProductoLocal(
  id: '5',
  nombre: 'GORRA STAYS AZUL OSCURO',
  descripcion: 'Diseño clásico "Stays" en azul oscuro, resistente y cómoda para uso diario.',
  precio: 85000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762950181/gorrastaysazulsocuro14_mt0k0o.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 15,
),
ProductoLocal(
  id: '6',
  nombre: 'GORRA VERDE A',
  descripcion: 'Gorra minimalista en verde fresco, ideal para combinar con cualquier outfit casual.',
  precio: 79000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762949686/gorraverdeA_tb21c5.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 9,
),
ProductoLocal(
  id: '7',
  nombre: 'GORRA VERDE Y AMARILLA B29',
  descripcion: 'Combinación audaz de verde y amarillo, para quienes buscan destacar con estilo.',
  precio: 88000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762949732/gorraverdeamarillab29_z5qcus.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 7,
),
ProductoLocal(
  id: '8',
  nombre: 'GORRA VERDE NY 31',
  descripcion: 'Inspirada en Nueva York, con bordado NY y tono verde militar, para amantes del streetwear.',
  precio: 93000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762949687/gorraverdeNY31_ps285t.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 11,
),
ProductoLocal(
  id: '9',
  nombre: 'GORRA AZUL Y ROJA W16',
  descripcion: 'Diseño dinámico con contraste azul y rojo, ideal para quienes aman los colores vibrantes.',
  precio: 87000,
  imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762950179/goorraazulyrojadew16_h36bi1.jpg',
  categoriaId: '1',
  tallas: ['Ajustable'],
  stock: 13,
),

  // DIM & A/N (3 productos)
  ProductoLocal(
    id: '10',
    nombre: 'GORRA NEGRA ALT. NACIONAL',
    descripcion: 'Diseño elegante con escudo bordado, ideal para uso casual y urbano.',
    precio: 82000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988183/negraconelescudo_zzh4l9.jpg',
    categoriaId: '2',
    tallas: ['Ajustable'],
    stock: 9,
  ),
  ProductoLocal(
    id: '11',
    nombre: 'GORRA NEGRA CON ESCUDO VERDE',
    descripcion: 'Variante con detalles verdes, para un estilo más fresco y juvenil.',
    precio: 84000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988184/negraconelescudoverde_pazamj.jpg',
    categoriaId: '2',
    tallas: ['Ajustable'],
    stock: 7,
  ),
  ProductoLocal(
    id: '12',
    nombre: 'GORRA VERDE NACIONAL ICON',
    descripcion: 'Inspirada en campaña atletico nacional, con colores y detalles únicos.',
    precio: 89000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988186/verdenacionalcon_knj0lf.jpg',
    categoriaId: '2',
    tallas: ['Ajustable'],
    stock: 11,
  ),

  // BEISBOLERA PREMIUM (6 productos)
  ProductoLocal(
    id: '13',
    nombre: 'GORRA AZUL BLANCO LA',
    descripcion: 'Clásico diseño de Los Angeles con contraste azul y blanco.',
    precio: 90000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910786/gorraazulblancoLA_rembf2.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 8,
  ),
  ProductoLocal(
    id: '14',
    nombre: 'GORRA AZUL CON TIPO A',
    descripcion: 'Estilo moderno con tipografía A, perfecta para el día a día.',
    precio: 88000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910795/gorraazulcontipoA_ldfroh.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 10,
  ),
  ProductoLocal(
    id: '15',
    nombre: 'GORRA AZUL RAYO',
    descripcion: 'Diseño dinámico con rayo bordado, ideal para amantes del estilo urbano.',
    precio: 92000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910797/gorraazulderayo_v8qcb0.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 6,
  ),
  ProductoLocal(
    id: '16',
    nombre: 'GORRA AZUL GRIS LA',
    descripcion: 'Combinación sobria de azul y gris con logo de Los Angeles.',
    precio: 87000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910786/gorraazulgrisLa_i1dazk.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 12,
  ),
  ProductoLocal(
    id: '17',
    nombre: 'GORRA AZUL LETRA VERDE B',
    descripcion: 'Detalles en verde que resaltan sobre fondo azul oscuro.',
    precio: 85000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910791/gorraazulletraverdeB_wb2htn.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 9,
  ),
  ProductoLocal(
    id: '18',
    nombre: 'GORRA AZUL TODA LA',
    descripcion: 'Diseño completo en azul con bordado LA, elegante y moderno.',
    precio: 91000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762910779/gorraazulltodaLA_ykxdvi.jpg',
    categoriaId: '3',
    tallas: ['Ajustable'],
    stock: 7,
  ),

  // DIAMANTE IMPORTADA (5 productos)
  ProductoLocal(
    id: '19',
    nombre: 'GORRA A ROJA',
    descripcion: 'Estilo minimalista con letra A en rojo vibrante.',
    precio: 93000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914404/gorraAroja_eypttd.jpg',
    categoriaId: '4',
    tallas: ['Ajustable'],
    stock: 6,
  ),
  ProductoLocal(
    id: '20',
    nombre: 'GORRA AS',
    descripcion: 'Diseño clásico con bordado AS, para amantes de lo vintage.',
    precio: 90000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914407/gorraAS_qybamm.jpg',
    categoriaId: '4',
    tallas: ['Ajustable'],
    stock: 8,
  ),
  ProductoLocal(
    id: '21',
    nombre: 'GORRA CON ROSAS',
    descripcion: 'Detalles florales bordados, ideal para un look diferente.',
    precio: 95000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914412/gorraconrosas_ko3326.jpg',
    categoriaId: '4',
    tallas: ['Ajustable'],
    stock: 5,
  ),
  ProductoLocal(
    id: '22',
    nombre: 'GORRA DOGE',
    descripcion: 'Inspirada en la cultura meme, con diseño de perro bordado.',
    precio: 88000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914410/gorradoge_mefwmo.jpg',
    categoriaId: '4',
    tallas: ['Ajustable'],
    stock: 10,
  ),
  ProductoLocal(
    id: '23',
    nombre: 'GORRA LA',
    descripcion: 'Clásico diseño de Los Angeles, elegancia y estilo urbano.',
    precio: 92000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914409/gorraLA_vz1fsr.jpg',
    categoriaId: '4',
    tallas: ['Ajustable'],
    stock: 9,
  ),


  // PLANA IMPORTADA (6 productos)
  ProductoLocal(
    id: '24',
    nombre: 'GORRA NEGRA A',
    descripcion: 'Diseño simple y elegante en negro con bordado A.',
    precio: 78000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995519/gorranegraA_yxzudv.jpg',
    categoriaId: '5',
    tallas: ['Ajustable'],
    stock: 12,
  ),
  ProductoLocal(
    id: '25',
    nombre: 'GORRA NEGRA AA',
    descripcion: 'Variante con doble A bordada, ideal para uso diario.',
    precio: 80000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995130/gorranegraAA_zkdg1e.jpg',
    categoriaId: '5',
    tallas: ['Ajustable'],
    stock: 10,
  ),
  ProductoLocal(
    id: '26',
    nombre: 'GORRA NEGRA AS',
    descripcion: 'Estilo urbano con bordado AS en negro mate.',
    precio: 82000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995520/gorranegraAS_mb6xsw.jpg',
    categoriaId: '5',
    tallas: ['Ajustable'],
    stock: 8,
  ),
  ProductoLocal(
    id: '27',
    nombre: 'GORRA NEGRA HEAT',
    descripcion: 'Inspirada en el equipo de Miami, con estilo moderno.',
    precio: 85000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995583/gorranegraheast_iji0cx.jpg',
    categoriaId: '5',
    tallas: ['7 1/4', '7 1/8', 'Ajustable'],
    stock: 11,
  ),
  ProductoLocal(
    id: '28',
    nombre: 'GORRA NEGRA HEATS',
    descripcion: 'Diseño premium con doble S, para amantes del streetwear.',
    precio: 87000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995585/gorranegraheatss_mphchc.jpg',
    categoriaId: '5',
    tallas: ['7', '7 1/4', 'Ajustable'],
    stock: 9,
  ),
  ProductoLocal(
    id: '29',
    nombre: 'GORRA NEGRA LAKERS',
    descripcion: 'Colores y logo oficial de los Lakers, estilo deportivo.',
    precio: 90000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762995518/gorranegralakers_a8wjwu.jpg',
    categoriaId: '5',
    tallas: ['7', '7 1/8', 'Ajustable'],
    stock: 7,
  ),

  // AGROPECUARIAS (5 productos)
  ProductoLocal(
    id: '30',
    nombre: 'GORRA AZUL CERDO VERDE',
    descripcion: 'Diseño rústico con cerdo bordado en tonos verdes.',
    precio: 75000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762916288/gorraazulcerdoverde_e10kc7.jpg',
    categoriaId: '6',
    tallas: ['Ajustable'],
    stock: 10,
  ),
  ProductoLocal(
    id: '31',
    nombre: 'GORRA AZUL TORO',
    descripcion: 'Estilo campesino con toro bordado, ideal para el campo.',
    precio: 77000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914771/gorraazultoro_h1mqjb.jpg',
    categoriaId: '6',
    tallas: ['Ajustable'],
    stock: 8,
  ),
  ProductoLocal(
    id: '32',
    nombre: 'GORRA BLANCA 2 GALLO',
    descripcion: 'Gallo bordado en blanco sobre fondo claro, diseño tradicional.',
    precio: 79000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914723/gorrablanca2gallo_rlwyl7.jpg',
    categoriaId: '6',
    tallas: ['Ajustable'],
    stock: 12,
  ),
  ProductoLocal(
    id: '33',
    nombre: 'GORRA BLANCA ADORNOS',
    descripcion: 'Detalles florales y bordados en hilo blanco.',
    precio: 81000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762914733/gorrablancaadornos_xszchs.jpg',
    categoriaId: '6',
    tallas: ['Ajustable'],
    stock: 9,
  ),
  ProductoLocal(
    id: '34',
    nombre: 'GORRA BLANCA CAFÉ',
    descripcion: 'Combinación de blanco y café con diseño campestre.',
    precio: 76000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762916297/gorrablancacafe_hdfpyx.jpg',
    categoriaId: '6',
    tallas: ['Ajustable'],
    stock: 11,
  ),

  // MULTIMARCA (8 productos)
  ProductoLocal(
    id: '35',
    nombre: 'GORRA MONASTERY MALLA',
    descripcion: 'Estilo moderno con malla trasera y diseño monastery.',
    precio: 94000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957915/gorramonasterymalla_o0rm13.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 7,
  ),
  ProductoLocal(
    id: '36',
    nombre: 'GORRA NEGRA UNDER LD',
    descripcion: 'Diseño urbano con logo Under LD en negro mate.',
    precio: 92000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957902/gorranegraundld_uh9wwr.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 9,
  ),
  ProductoLocal(
    id: '37',
    nombre: 'GORRA AMIRI BLANCA',
    descripcion: 'Estilo premium con logo Amiri en blanco.',
    precio: 96000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957956/gorraamiriblanca_xuguvk.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 6,
  ),
  ProductoLocal(
    id: '38',
    nombre: 'GORRA AMIRI GRIS',
    descripcion: 'Variante en gris con bordado Amiri, elegante y moderna.',
    precio: 95000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957961/gorraamirigris_km4asg.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 8,
  ),
  ProductoLocal(
    id: '39',
    nombre: 'GORRA AMIRI PLATEADA',
    descripcion: 'Detalles en plateado que resaltan en fondo gris oscuro.',
    precio: 97000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957952/gorraamiriplaeada_ugwmxz.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 5,
  ),
  ProductoLocal(
    id: '40',
    nombre: 'GORRA BLANCA NEGRA CLEMONT',
    descripcion: 'Diseño exclusivo Clemont con contraste blanco y negro.',
    precio: 93000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957947/gorrablanca-negraclemont_cofoqg.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 10,
  ),
  ProductoLocal(
    id: '41',
    nombre: 'GORRA BLANCA ROSA',
    descripcion: 'Estilo juvenil con detalles en rosa pastel.',
    precio: 90000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957944/gorrablancarosa_tt88y8.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 11,
  ),
  ProductoLocal(
    id: '42',
    nombre: 'GORRA SUPREME JORDAN',
    descripcion: 'Colaboración entre Supreme y Jordan, diseño exclusivo.',
    precio: 98000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762957885/gorrasuepremejordan_namavp.jpg',
    categoriaId: '7',
    tallas: ['Ajustable'],
    stock: 4,
  ),

  // PLANA CERRADA 1.1 (6 productos)
  ProductoLocal(
    id: '43',
    nombre: 'GORRA AZUL NY',
    descripcion: 'Diseño clásico de Nueva York en tono azul.',
    precio: 86000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988571/gorraazulNY_huym2t.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 9,
  ),
  ProductoLocal(
    id: '44',
    nombre: 'GORRA BLANCA BUKS',
    descripcion: 'Estilo limpio con logo BUKS en blanco.',
    precio: 84000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988568/gorrablancabuks_ll8ymc.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 11,
  ),
  ProductoLocal(
    id: '45',
    nombre: 'GORRA NEGRA CELTICS',
    descripcion: 'Colores y logo oficial de los Celtics, estilo deportivo.',
    precio: 89000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988567/gorranegraceltics_isriex.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 8,
  ),
  ProductoLocal(
    id: '46',
    nombre: 'GORRA NEGRA JORDAN',
    descripcion: 'Logo Jordan bordado en negro, diseño premium.',
    precio: 91000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988576/gorranegrajordan_arghad.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 7,
  ),
  ProductoLocal(
    id: '47',
    nombre: 'GORRA NEGRA LARKES',
    descripcion: 'Estilo urbano con logo Larkes en blanco.',
    precio: 87000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988574/gorranegralarkes_wia94w.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 10,
  ),
  ProductoLocal(
    id: '48',
    nombre: 'GORRA NEGRA TORO',
    descripcion: 'Diseño campestre con toro bordado en negro.',
    precio: 83000,
    imagenUrl: 'https://res.cloudinary.com/dxc5qqsjd/image/upload/v1762988588/gorranegratoro_t9ycan.jpg',
    categoriaId: '8',
    tallas: ['7', '7 1/4', '7 1/8'],
    stock: 12,
  ),
];
