// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJpLdYfIxmbq35CYB52v1V_mmY1v5rBBQ',
    appId: '1:740630978018:web:f6940a92ad969f99da2dbb',
    messagingSenderId: '740630978018',
    projectId: 'streetmovil-e733c',
    authDomain: 'streetmovil-e733c.firebaseapp.com',
    storageBucket: 'streetmovil-e733c.firebasestorage.app',
    measurementId: 'G-YZ716FGG09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WGJbccUacJ1BRMNmTBI4c2a2ykbTEXk',
    appId: '1:740630978018:android:7c98e49f308c3e70da2dbb',
    messagingSenderId: '740630978018',
    projectId: 'streetmovil-e733c',
    storageBucket: 'streetmovil-e733c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbqZROAtuXxK5Sk3Nq9jMzSgTfbaCKcQI',
    appId: '1:740630978018:ios:27b1f7a95e338702da2dbb',
    messagingSenderId: '740630978018',
    projectId: 'streetmovil-e733c',
    storageBucket: 'streetmovil-e733c.firebasestorage.app',
    iosBundleId: 'com.example.streetmovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbqZROAtuXxK5Sk3Nq9jMzSgTfbaCKcQI',
    appId: '1:740630978018:ios:27b1f7a95e338702da2dbb',
    messagingSenderId: '740630978018',
    projectId: 'streetmovil-e733c',
    storageBucket: 'streetmovil-e733c.firebasestorage.app',
    iosBundleId: 'com.example.streetmovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJpLdYfIxmbq35CYB52v1V_mmY1v5rBBQ',
    appId: '1:740630978018:web:e220e1a506faf4a2da2dbb',
    messagingSenderId: '740630978018',
    projectId: 'streetmovil-e733c',
    authDomain: 'streetmovil-e733c.firebaseapp.com',
    storageBucket: 'streetmovil-e733c.firebasestorage.app',
    measurementId: 'G-ZZ9SHVQTY2',
  );
}
